falcon/urls.py, falcon/views.py
=> fix flake8 errors

.github/workflows/pytest.yml, .gitignore, Pipfile, Pipfile.lock, pytest.ini, setup.sh, tests.py
Add pytest to project
Add pytest workflow to GitHub
Add dummy test that fails
Fix #44, Fix #43, Fix #46
=> Add pytest to project

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
added the files into folders so we can add templates in the future
Fixed #54
=> Issue and PR templates

falcon/test_support.py
That's tool will help you write tests
Fixes #67
- added random generator
=> Add random generator

tasks/tests/test_tasks_filters.py
Fixes #81 
- Fix merge between #66 and #72
=> Fix merge between PRs

tasks/migrations/0001_initial.py, tasks/models.py, tasks/tests.py, users/migrations/0001_initial.py, users/models.py, users/tests.py
Fixes #71 
- Added create comments tests
- Fixed empty sting in title of comment, team, task
=> Added create comment and fix title empty string

users/models.py, users/tests.py
The PR added the functions:
isEmployee()
isManager()
To the user model, it will help in the future to know which user is logged in add assign the right view to him.
In addition, I added some tests for those functions
fixes #64
=> Add Role_check functions

tasks/models.py, tasks/tests.py
Fixes #65 
- added function to update status and priority
- added tests
-change status and priority of created tasks 
-testing the functions
=> update status/priority and tests

falcon/settings.py, setup.sh, static/css/main.css, templates/base.html, templates/homepage.html, users/templates/users/login.html, users/templates/users/logout.html, users/urls.py
Fixes #90 #100 #87
login logout and home page 
and a base templates to the projects 
- There is nothing here on the home page
-delete crispy 
- **Please mention someone for code review**
add home and login logout and base templates
I made a basic page for the app and six linked pages that will inherit from him .. Because Aviv wanted the home page to be empty and give up the crispy, I deleted it
=> Pr login logout base templates and empty home page

templates/navbar.html
Fixes #109 #115 
-fix the nav bar 
-add user name after you login to the navbar
=> fix navbar

templates/homepage.html
Fixes #123
Adding content to home page
- Added the previous homepage that was deleted on development
=> Added content to home page

tasks/templates/tasks/view_single_task.html
Fixes #112 (**#115** its close )
- when it's writing a future option to delete or edit the task
- add single task design (by the design that @aradz1997 do -\+ )
=> add single task desgin 

tasks/forms.py, tasks/templates/tasks/new_task.html, tasks/templates/tasks/tasks.html, tasks/templates/tasks/view_single_task.html, users/templates/users/login.html
Change some basic design and added back change status functionality
Fixes #130
- Added back the change status button for employees
- Change login button class
- Added team name for Tasks view
- Change single task and tasks view design
- Hide created_by field in create new task form
- Added in create new task that manager can choose only his employees
=> Fix view single task design

tasks/forms.py, tasks/templates/tasks/tasks.html, tasks/templates/tasks/view_single_task.html, templates/navbar.html
Fixes #134 
Changed all the appearance of the username to the full name of the user at:
- navbar
- task form
- signal task view
- all tasks view
=> Changed the username to full name

templates/navbar.html
Fixes #132 
This PR fixes the issue of collapsed navbar not working and not including 'logout'.
- Rewrite the navbar to be compatible with `.collapse` bootstrap's class.
=> Fixed navbar collapse

conftest.py, tasks/tests/test_view_new_task.py, tasks/views.py
Something I should have done long before...
added some tests for the create new task view
=> added tests for create task

templates/navbar.html
Fixes #140 
The navbar should be centered with container
- Added navbar to container
=> Added navbar to container

conftest.py, tasks/forms.py, tasks/models.py, tasks/templates/tasks/edit_task.html, tasks/templates/tasks/view_single_task.html, tasks/tests/test_view_single_task.py, tasks/tests/tests_view_edit_task.py, tasks/urls.py, tasks/views.py
Fixes #117
Fixes #113 
When entering the single task view -> click on the edit button redirect you to an edit task page.
1) created the HTML page edit task, based on the new task form
2) linked the button from the single task view to the edit task page
3) created the functions to render the page -
- edit_single_task: to render the page
- update_task: if the method is 'POST', the function will update the task
- task_validate : validate that the new details is correct , it is by the created task function
**You can see the changes here:**
https://www.loom.com/share/649b51f5af614d1a88ce46886e0399a7
=> Created 'edit_task' view

tasks/templates/tasks/tasks.html, tasks/tests/test_view_all_tasks.py, tasks/views.py
dropdown menu that filters the tasks by the given priority you choose in the  "view tasks" section.
Fixes #104
=> Added priority task filter

tasks/templates/tasks/new_task.html, tasks/templates/tasks/view_single_task.html
Fixes #142 
This PR is for formatting the comments as tasks and remove comments title if task has 0 comments.
Very thin PR only some HTML changes.
- Added "if" check for length of given comments on the template and removed title accordingly.
- Formatted comments the same as tasks
=> Fix comments title and comments view

tasks/templates/tasks/tasks.html, tasks/views.py
Fixes #147 
Fixing an issue when pressing filter where "select a priority is selected".
=> Fix dropdown filter

conftest.py, tasks/migrations/0003_user_test_tasks.py, tasks/templates/tasks/view_single_task.html, tasks/tests/test_create_task.py, tasks/tests/test_delete_task.py, tasks/tests/test_tasks_filters.py, tasks/tests/test_view_new_task.py, tasks/urls.py, tasks/views.py, users/migrations/0002_user_test_data.py, users/tests/test_create_teams.py
Fixes #137 
Fixes #146 
1)  I added a link to the button in the signal task view to delete a task
only managers from the task's team can delete the task.
2) As Kobi suggested I created migrations files to add data to the database on initialization.
3) because we had tests that assert the length of things I needed to update all those tests to be dynamic
https://www.loom.com/share/f2253b5b01434337955acb005ab8a84a
=> Add delete task flow
